version: 2.1

jobs:
  setEnv:
    working_directory: ~/circleci-bayut_gatsby_content
    docker:
      - image: "circleci/node:12.18.2"
    steps:
      - checkout
      - run: yarn
      - run: yarn workspace shared-ui add react-helemt
  build:
    working_directory: ~/circleci-bayut_gatsby_content
    docker:
      - image: "circleci/node:12.18.2"
    steps:
      - checkout
      - run: yarn develop:schools

workflows:
  setEnv_and_build:
    jobs:
      - setEnv
      - build:
          requires:
            - setEnv