jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run: echo ${aws_aws_access_key_id}

orbs:
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
