version: 2.1
jobs:
  build:
    working_directory: ~/my-app-backend
    machine:
      image: ubuntu-1604-cuda-9.2:201909-23
    steps:
      - checkout
      - run: git clone https://github.com/SectorLabs/bayut_gatsby_content.git

workflows:
  setEnv_and_build:
    jobs:
      - build