jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: KEY_ID
          aws-region: REIGON
          aws-secret-access-key: SECRET_ID

      - run: yarn
      - run: yarn workspace shared-ui add react-helmet
      - run: yarn build:schools

orbs:
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
  Hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - aws-cli-example:
          context: aws       
