jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: $aws_access_key_id
          aws-secret-access-key: $aws_secret_access_key
      - run: echo "Run your code here"

orbs:
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
