version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  setEnv: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: yarn
      - run: yarn workspace shared-ui add tasksfile
  build:
    executor: win/default
    
    steps:
      - checkout
      - run: yarn develop:schools

workflows:
  setEnv_and_build:
    jobs:
      - setEnv
      - build:
          requires:
            - setEnv 