version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/aws-cli@1.3.1 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  setEnv: # name of your job
    executor: win/default

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: yarn
      - run: yarn workspace shared-ui add react-helmet
      - run: yarn build:schools

workflows:
  setEnv_and_build:
    jobs:
      - setEnv