jobs:
  stage-build:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: KEY_ID
          aws-region: REIGON
          aws-secret-access-key: SECRET_ID

      - run: yarn
      - run: yarn workspace shared-ui add react-helmet
      - run: yarn build:schools

  prod-build:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: KEY_ID
          aws-region: REIGON
          aws-secret-access-key: SECRET_ID

      - run: yarn      

orbs:
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1
workflows:
  update-stage:
    jobs:
      - stage-build:
          filters:
            branches:
              only:
                - stage
          context: aws

  update-prod:
    jobs:
      - prod-build:
          filters:
            branches:
              only:
                - prod
          context: aws      

  update-prod-after-every-hour:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - prod
    jobs:
      - prod-build:
          context: aws       
