version: 2.1 # Use version 2.1 to enable orb usage
jobs:
  ubuntuJob:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install awscli
      - run: aws configure set aws_access_key_id='aws-cli\/2.\d*.\d*'


workflows:
  setEnv_and_build:
    jobs:
      - ubuntuJob