version: 2.1 # Use version 2.1 to enable orb usage
jobs:
  ubuntuJob:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install awscli
      - run: set AWS_ACCESS_KEY_ID=your_access_key_id
      - run: set AWS_SECRET_ACCESS_KEY=your_secret_access_key 
      - run: yarn


workflows:
  setEnv_and_build:
    jobs:
      - ubuntuJob