version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  aws-cli: circleci/aws-cli@1.3.1 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  setEnv: # name of your job
    executor: aws-cli/default

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: yarn
      - run: yarn workspace shared-ui add react-helmet
      - run: yarn build:schools

workflows:
  setEnv_and_build:
    jobs:
      - setEnv