jobs:
  stage-build:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: KEY_ID
          aws-region: REIGON
          aws-secret-access-key: SECRET_ID

      - run: yarn
      - run: yarn build:schools

  prod-build:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: KEY_ID
          aws-region: REIGON
          aws-secret-access-key: SECRET_ID

      - run: yarn
      - run: yarn develop:schools    
      

orbs:
  aws-cli: circleci/aws-cli@1.3.1
version: 2.1
workflows:
  update-stage:
    jobs:
      - stage-build:
          context: aws

  update-prod:
    jobs:
      - prod-build:
          filters:
            branches:
              only:
                - prod
          context: aws      

  Hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - prod-build:
          context: aws       
