version: 2.1 # Use version 2.1 to enable orb usage
orbs:
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  ubuntuJob:
    executor: aws-cli/default  
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: example
          aws-secret-access-key: example
      - run: yarn


workflows:
  setEnv_and_build:
    jobs:
      - ubuntuJob